apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime-chat-api-ingress
  namespace: backend
spec:
  tls:
  - secretName: meu-tls
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: realtime-chat-api-service
            port:
              number: 5001
